podSpec:
  restartPolicy: Never
  serviceAccountName: sonobuoy-serviceaccount
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists
  - key: CriticalAddonsOnly
    operator: Exists
  containers:
    - name: report-progress
      image: image-registry.openshift-image-registry.svc:5000/openshift/tests:latest 
      command: 
      - /bin/sh
      - -c
      - >                
        sleep 10;        
        PASSED=0;
        FAILURES="";        
        HAS_UPDATE=0;
        while read line; 
        do
            JOB_PROGRESS=$(echo $line | grep -Po "\([0-9]{1,}\/[0-9]{1,}\/[0-9]{1,}\)");            
            if [ ! -z "${JOB_PROGRESS}" ]; then              
              TOTAL=$(echo ${JOB_PROGRESS:1:-1} | cut -d'/' -f 3);  
              HAS_UPDATE=1;                          
            elif [[ $line == passed:* ]] || [[ $line == skipped:* ]]; then
              PASSED=$((PASSED + 1));
              HAS_UPDATE=1;
            elif [[ $line == failed:* ]]; then              
              if [ -z "${FAILURES}" ]; then
                FAILURES=\"$(echo $line | cut -d"\"" -f2)\"
              else
                FAILURES=,\"$(echo $line | cut -d"\"" -f2)\"
              fi
              HAS_UPDATE=1;
            fi
            if [ $HAS_UPDATE -eq 1 ]; then
              curl -v http://127.0.0.1:8099/progress -d "{\"completed\":$PASSED,\"total\":$TOTAL,\"failures\":[$FAILURES]}";
              HAS_UPDATE=0;
            fi
            JOB_PROGESS="";
        done <"/tmp/sonobuoy/results/status_pipe"
      volumeMounts:
      - mountPath: /tmp/sonobuoy/results
        name: results
sonobuoy-config:
  driver: Job
  plugin-name: openshift-e2e-cert
  result-format: junit
spec:
  command:
  - /bin/sh
  - -c
  - >        
    mkfifo /tmp/sonobuoy/results/status_pipe; 
    export KUBECONFIG=/tmp/kubeconfig;
    oc login https://172.30.0.1:443 --token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token) --certificate-authority=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt;
    PUBLIC_API_URL=$(oc get infrastructure cluster -o=jsonpath='{.status.apiServerURL}');
    oc login ${PUBLIC_API_URL} --token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token) --certificate-authority=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt;       
    openshift-tests run --junit-dir /tmp/sonobuoy/results openshift/conformance/parallel | tee /tmp/sonobuoy/results/status_pipe
    RESULT=$?;
    echo RESULT ${RESULT};
    cd /tmp/sonobuoy/results;
    JUNIT_OUTPUT=$(ls junit*.xml);
    chmod 644 ${JUNIT_OUTPUT};
    echo '/tmp/sonobuoy/results/'${JUNIT_OUTPUT} > /tmp/sonobuoy/results/done     
  image: image-registry.openshift-image-registry.svc:5000/openshift/tests:latest 
  name: plugin
  resources: {}
  volumeMounts:
  - mountPath: /tmp/sonobuoy/results
    name: results

